apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.lightdashConfigMap | nindent 2 }}
  {{- toYaml .Values.emailConfigMap | nindent 2 }}
  {{- toYaml .Values.databaseConfigMap | nindent 2 }}
